### ISSUE TITLE
[feature request] add ability to post

### ISSUE THREAD

**Issue by ryanrms** [tabasku/harbour-neliapila#2]
nice app! I would like the abilty to post from within the app.  i guess we would need the ability to do catchpas in the app and/or add support for 4chan pass.  Android apps are probably built very differently, but perhaps you could look to Clover for inspiration and possibly liberate some code?  It's licensed under the GPL as well.

**Comment by tabasku** [comment]
Thanks! I have been trying to wrap my head around posting lately. Actually posting itself should not be too hard to implement but I'm bit stuck with how to show Captcha properly from app. 

Clover seems to be able to show reCaptcha widget on WebView. However when I'm trying same with SilicaWebView I get following error from widget `Domain is not in the list of supported domains for this site key.`. So next I probably need to find way to modify headers (Referrer) sent from Webview so that widget thinks we are using right domain.

Other way would be displaying Captcha in QML and scraping widget with Python but that might be prone to break easily if Google makes some changes to widget.

**Comment by szopin** [comment]
This seems to be fixed and working nicely (with just a small bug when replying to a thread that gets 404'd it displays: you are banned, which was a bit shocking first time I've encountered it)

**Comment by szopin** [comment]
Also happens when replying to nested posts (either from view replies or after following >> link)

**Comment by tabasku** [comment]
Closing this issue and created new one for better POST response handling https://github.com/tabasku/harbour-neliapila/issues/11
