### ISSUE TITLE
Reset settings closes the app

### ISSUE THREAD

**Issue by szopin** [tabasku/harbour-neliapila#38]
[W] unknown:66 - file:///usr/share/harbour-neliapila/qml/js/settingsStorage.js:66: Error: no such table: settings Unable to execute statement
[D] unknown:0 - "No carrier"

This was the console output

**Comment by jacquesCedric** [comment]
Resetting the app is intentional as some settings wouldn't take place. The table error is unexpected but I imagine it's due to the the way the settings are restarted.
Despite being initialized at app start, the threads page must be calling something first. The only side-effect of this should be the quickscroll setting not working as expected on the board view. Will look into fixing this.

**Comment by szopin** [comment]
Oh ok, probably will be enough to mention app will close or app needs to be restarted, as from the current wording I assumed just settings will be cleared and thought it crashed

**Comment by jacquesCedric** [comment]
Yeah, you're right. It should be done better.

How about, "Neliapila will exit after this (irreversible) action!" for the sublabel and, "Clearing settings and restarting app" for the remorsepopup text?

**Comment by szopin** [comment]
That should work, thanks!

**Comment by jacquesCedric** [comment]
Pushed
